# Generated by Django 4.2.5 on 2023-12-26 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last activity'),
        ),
    ]
