# Generated by Django 4.2.5 on 2023-09-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('text', models.TextField(verbose_name='Text')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview')),
                ('made_date', models.DateField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('last_update', models.DateField(blank=True, default=None, null=True, verbose_name='Last update date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publication Status')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Number of Views')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='MaterialPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Signature')),
                ('figure', models.ImageField(upload_to='', verbose_name='Figure')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_content.material')),
            ],
            options={
                'verbose_name': 'Figure',
                'verbose_name_plural': 'Figures',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview')),
                ('made_date', models.DateField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('last_update', models.DateField(blank=True, default=None, null=True, verbose_name='Last update date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publication Status')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
    ]
