# Generated by Django 4.2.5 on 2023-09-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0003_alter_chapter_owner_alter_material_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Views'),
        ),
    ]
