# Generated by Django 4.2.5 on 2023-09-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0005_alter_chapter_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education_content.chapter'),
            preserve_default=False,
        ),
    ]
