# Generated by Django 4.2.5 on 2023-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0006_material_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_published_requested',
            field=models.BooleanField(default=False, verbose_name='Publication request status'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_published_requested',
            field=models.BooleanField(default=False, verbose_name='Publication request status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publication status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of views'),
        ),
    ]
