# Generated by Django 4.2.5 on 2023-10-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0010_alter_chapter_last_update_alter_material_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_test_exist',
            field=models.BooleanField(default=False, verbose_name='Test exist status'),
        ),
    ]
