# Generated by Django 4.2.5 on 2023-11-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0012_alter_material_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialphotos',
            name='figure_3d',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='materialphotos',
            name='figure',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Figure'),
        ),
    ]
