# Generated by Django 4.2.5 on 2023-11-10 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0013_materialphotos_figure_3d_alter_materialphotos_figure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update time'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='made_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='material',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update time'),
        ),
        migrations.AlterField(
            model_name='material',
            name='made_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
    ]
