# Generated by Django 4.2.5 on 2023-11-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0003_mineral_label'),
        ('education_content', '0015_remove_materialphotos_figure_3d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialphotos',
            old_name='figure',
            new_name='preview',
        ),
        migrations.AddField(
            model_name='materialphotos',
            name='p3din_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_content.figurefromp3din', verbose_name='Model from p3d.in'),
        ),
        migrations.AddField(
            model_name='materialphotos',
            name='thin_section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_content.figurethinsection', verbose_name='Thin Section'),
        ),
        migrations.AlterField(
            model_name='materialphotos',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_content.material', verbose_name='Material'),
        ),
    ]
