# Generated by Django 4.2.5 on 2024-01-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0017_remove_materialphotos_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_login_required',
            field=models.BooleanField(default=True, verbose_name='Login required status'),
        ),
    ]
