# Generated by Django 4.2.5 on 2024-02-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0018_figure360view_preview'),
        ('education_content', '0018_material_is_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialphotos',
            name='pano_view',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unique_content.figure360view', verbose_name='360 view'),
        ),
    ]
