# Generated by Django 4.2.5 on 2024-02-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_content', '0019_materialphotos_pano_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialphotos',
            name='map',
            field=models.BooleanField(default=False, verbose_name='Map implementation'),
        ),
    ]
