# Generated by Django 4.2.5 on 2023-11-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurethinsection',
            name='file',
        ),
        migrations.RemoveField(
            model_name='figurethinsection',
            name='is_ppl',
        ),
        migrations.AddField(
            model_name='figurethinsection',
            name='file_cpl',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='File CPL'),
        ),
        migrations.AddField(
            model_name='figurethinsection',
            name='file_ppl',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='File PPL'),
        ),
    ]
