# Generated by Django 4.2.5 on 2023-11-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0002_remove_figurethinsection_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=100, verbose_name='Mineral name(Eng)')),
                ('name_rus', models.CharField(max_length=100, verbose_name='Mineral name(Rus)')),
                ('abbreviation', models.CharField(max_length=4, verbose_name='Mineral abbreviation')),
            ],
            options={
                'verbose_name': 'Mineral',
                'verbose_name_plural': 'Minerals',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_X', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Label X coordinate on the video')),
                ('coord_Y', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Label Y coordinate on the video')),
                ('figure_thin_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_content.figurethinsection')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_content.mineral')),
            ],
            options={
                'verbose_name': 'Mineral signature label',
                'verbose_name_plural': 'Mineral signature labels',
            },
        ),
    ]
