# Generated by Django 4.2.5 on 2023-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0003_mineral_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurethinsection',
            name='preview_cpl',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview CPL'),
        ),
        migrations.AddField(
            model_name='figurethinsection',
            name='preview_ppl',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview PPL'),
        ),
    ]
