# Generated by Django 4.2.5 on 2023-11-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0004_figurethinsection_preview_cpl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurefromp3din',
            name='link_for_iframe',
            field=models.URLField(blank=True, max_length=302, null=True, verbose_name='Link to p3d.in iframe'),
        ),
        migrations.AlterField(
            model_name='figurefromp3din',
            name='link',
            field=models.URLField(max_length=300, verbose_name='Link to p3d.in'),
        ),
    ]
