# Generated by Django 4.2.5 on 2024-01-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0006_alter_mineral_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurefromp3din',
            name='is_login_required',
            field=models.BooleanField(default=True, verbose_name='Login required status'),
        ),
        migrations.AddField(
            model_name='figurethinsection',
            name='is_login_required',
            field=models.BooleanField(default=True, verbose_name='Login required status'),
        ),
    ]
