# Generated by Django 4.2.5 on 2024-01-29 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unique_content', '0007_figurefromp3din_is_login_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure360View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('view', models.ImageField(upload_to='', verbose_name='View')),
                ('made_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update time')),
                ('is_login_required', models.BooleanField(default=True, verbose_name='Login required status')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('image_creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Image Creation Date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': '360 view',
                'verbose_name_plural': '360 view',
            },
        ),
    ]
