# Generated by Django 4.2.5 on 2024-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0008_figure360view'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure360view',
            name='pano_type',
            field=models.CharField(choices=[('air', 'Aerial panorama'), ('ground', 'Ground panorama'), ('other', 'Other type')], default='air', max_length=6, verbose_name='Panorama type'),
        ),
    ]
