# Generated by Django 4.2.5 on 2024-01-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0010_infospotforpanorama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infospotforpanorama',
            name='coord_X',
        ),
        migrations.RemoveField(
            model_name='infospotforpanorama',
            name='coord_Y',
        ),
        migrations.RemoveField(
            model_name='infospotforpanorama',
            name='coord_Z',
        ),
        migrations.RemoveField(
            model_name='infospotforpanorama',
            name='panorama',
        ),
        migrations.RemoveField(
            model_name='infospotforpanorama',
            name='text',
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='title',
            field=models.CharField(default='text', max_length=100, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InfoSpotCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_X', models.FloatField(verbose_name='X coord')),
                ('coord_Y', models.FloatField(verbose_name='Y coord')),
                ('coord_Z', models.FloatField(verbose_name='Z coord')),
                ('info_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_content.infospotforpanorama')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_content.figure360view')),
            ],
            options={
                'verbose_name': 'Info spot coordinates',
                'verbose_name_plural': 'Info spot coordinates',
            },
        ),
    ]
