# Generated by Django 4.2.5 on 2024-01-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0011_remove_infospotforpanorama_coord_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infospotforpanorama',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='LinkSpotCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('coord_X', models.FloatField(verbose_name='X coord')),
                ('coord_Y', models.FloatField(verbose_name='Y coord')),
                ('coord_Z', models.FloatField(verbose_name='Z coord')),
                ('panorama_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_from_coordinates', to='unique_content.figure360view')),
                ('panorama_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_to_coordinates', to='unique_content.figure360view')),
            ],
            options={
                'verbose_name': 'Link spot coordinates',
                'verbose_name_plural': 'Link spot coordinates',
            },
        ),
    ]
