# Generated by Django 4.2.5 on 2024-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0013_alter_linkspotcoordinates_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospotforpanorama',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
