# Generated by Django 4.2.5 on 2024-02-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0014_infospotforpanorama_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospotforpanorama',
            name='figure_3d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unique_content.figurefromp3din'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='figure_thin_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unique_content.figurethinsection'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview'),
        ),
        migrations.AddField(
            model_name='infospotforpanorama',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Video link'),
        ),
    ]
