# Generated by Django 4.2.5 on 2024-02-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0016_infospotforpanorama_youtube_for_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure360view',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor'),
        ),
    ]
