# Generated by Django 4.2.5 on 2024-02-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0017_figure360view_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure360view',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview'),
        ),
    ]
