# Generated by Django 4.2.5 on 2024-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0018_figure360view_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure360view',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='figurefromp3din',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='figurethinsection',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
