# Generated by Django 4.2.5 on 2023-10-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquestion',
            name='completed_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.completedtest', verbose_name='Completed Test'),
        ),
    ]
