# Generated by Django 4.2.5 on 2023-11-10 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update teme'),
        ),
        migrations.AlterField(
            model_name='test',
            name='made_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
    ]
