# Generated by Django 4.2.5 on 2024-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_test_last_update_alter_test_made_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
